version: "1.0"

services:
  egrn_bot:

    build:
      platforms:
        - "linux/amd64"
      context: .
      dockerfile: Dockerfile
    container_name: egrn_bot
    restart: always
    command: sh -c "python main.py"
    env_file:
      - .env
    volumes:
      - ./logs:/bot/logs