version: "1.0"

services:
#  egrn_selenium_driver:
#    image: selenium/standalone-chrome:3.141.59-20210607
#    ports:
#      - "4444:4444"
##    --disable-dev-shm-usage
#    restart: always
  egrn_bot:
    build:
#      platforms:
#        - "linux/amd64"
      context: .
      dockerfile: Dockerfile
    container_name: egrn_bot
    restart: always
    command: sh -c "uvicorn main:app --port 9999 --host 0.0.0.0"
#    command: sh -c "python main.py"
    env_file:
      - .env
    volumes:
      - ./migrations/versions:/code/migrations/versions
      - ./logs:/bot/logs
      - ./bot/bot_data.pickle:/bot/bot/bot_data.pickle
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: mkd_database
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "5430:5432"
    env_file:
      - .env

volumes:
  postgres_data:
