version: "1.0"

services:
  #  egrn_selenium_driver:
  #    image: selenium/standalone-chrome:3.141.59-20210607
  #    ports:
  #      - "4444:4444"
  ##    --disable-dev-shm-usage
  #    restart: always
  egrn_bot:
    build:
      #      platforms:
      #        - "linux/amd64"
      context: .
      dockerfile: Dockerfile
    container_name: egrn_bot
    restart: always
    command: sh -c "uvicorn main:app --port 9999 --host 0.0.0.0"
    #    command: sh -c "python main.py"
    env_file:
      - .env
    volumes:
      - ./migrations/versions:/bot/migrations/versions
      - ./logs:/bot/logs
      - ./bot/bot_data.pickle:/bot/bot/bot_data.pickle
      - ./files:/bot/files
    depends_on:
      - db
    ports:
      - "9999:9999"
  db:
    image: postgres:15
    container_name: egrn_database
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "5430:5432"
    env_file:
      - .env
  redis:
    image: redis:6.2.5
    container_name: egrn_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    #    volumes:
    #      - redis_data:./redis_datapadeswx
    env_file:
      - .env
  arq_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: egrn_worker
    restart: always
    command: sh -c "arq arq_app.WorkerSettings"
  flower:
    image: mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - 5557:5555
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
